kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.52.13.37
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: kafka1:1:1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: skp
  name: skp
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: skp
    spec:
      containers:
      - image: tato30/sopes-kafka-producer
        name: sopes-kafka-producer
        resources: {}
        env:
          - name: KAFKA_URL
            value: "10.52.13.37:9092"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: skp-service
  name: skp
  namespace: squidgame
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: skp
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sks
  name: sks
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sks
    spec:
      containers:
      - image: tato30/sopes-kafka-consumer
        name: sopes-kafka-consumer
        resources: {}
        env:
        - name: KAFKA_URL
          value: "10.52.13.37:9092"
status: {}
