apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-httpd
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: '30s'
  selector:
    namespaces:
  		- squidgame 
    labelSelectors:
      "app": "matarpod"
